### ISSUE TITLE
not quite picking up the language

### ISSUE THREAD

**Issue by lewislepton** [vshaxe/vshaxe#107]
on making new files, haxe is not really picked up fully. case in point, Float, Int. not picked up unless typed out first.
guess this may be due to something else, but just want to bring it up ;)

<img width="585" alt="screen shot 2017-03-14 at 20 36 38" src="https://cloud.githubusercontent.com/assets/11299322/23921330/34a10056-08f6-11e7-93e3-38bf737237f1.png">

**Comment by Gama11** [comment]
This is very likely due to the [Completion Cache](https://github.com/vshaxe/vshaxe/wiki/Completion-Cache) not being initialized yet - before that's done, completion requests won't go through, since the compilation server is busy.

I hope we can make this a bit more intuitive / discoverable in the future. I think there's some "progress-bar-API" planned for VSCode's extension API, which we might be able to use: https://github.com/Microsoft/vscode/issues/18066

**Comment by lewislepton** [comment]
ah ok. cool ;)

**Comment by Gama11** [comment]
I've opened a separate issue as a reminder: #108
