### ISSUE TITLE
Organize our marketplace offerings?

### ISSUE THREAD

**Issue by jcward** [vshaxe/vshaxe#11]
Hey @nadako and @Simn -

Are you interested in coordinating the VSCode marketplace offerings? I think there's a few oddities with the current state:

- There are two Haxe extensions currently titled **haxe** and **Haxe Support**.
- One publisher is **haxedevs** and the other is **nadako**.

It seems a bit scattered and unofficial.

I think a nice arrangement would be to have the publisher be **Haxe Foundation**, with both a **Haxe** extension (vshaxe) and something like **Legacy Haxe 3.2.1** extension (vscode-haxe). I don't mind vscode-haxe being labelled legacy as I don't plan on putting more effort into it, and it looks like you guys are actively developing vshaxe with the latest compiler features. Maybe one day we'd remove the legacy plugin entirely.

However, I'm not sure whether we can technically change the names of either the plugins or the publishers (I got stuck on lowercase haxe because of that.) We'd have to look into that - maybe email support? If we had to remove and publish new extensions, that wouldn't be ideal as 1) we'd lose our download counts (which imply Haxe's popularity is higher than dart :smile: ), and 2) current users wouldn't get auto-update notifications.

If we can keep our plugins and download counts and change names, I'd be happy to send my publishing keys to the Haxe Foundation.

Thoughts?

**Comment by nadako** [comment]
Hey @jcward, thanks for bringing up this topic. I was going to write you about this at some point, trying to explain the reasoning behind developing a new plugin instead of joining vscode-haxe. I feel like I should do it now.

The main reason was because I found this awesome [Language Server Protocol](https://github.com/Microsoft/language-server-protocol/) designed by Microsoft. It's already supported in VS Code, but the idea is that it can be also used by other editors, so having a IDE-agnostic language server for Haxe still strikes me as a great idea. I started developing the language server and then developed a VSCode plugin to actually use it. Refactoring vscode-haxe would be much harder to do.

Also, I wanted the VSCode plugin and the language server to have as less workarounds as possible and rely on the Haxe compiler as much as possible, and also be completely framework-agnostic, so I designed it in this minimalistic way. Changing vscode-haxe instead would lead to breakage and feature removal, so I didn't do that too. On the other hand, this lead to fixing and adding A LOT of stuff to Haxe itself, such as stdio-based protocol, in-memory display files and new features (e.g. "document symbols"), so I'm very satisfied with its current state.

I hope that clears things up! Now to the actual issue...

We can change the name shown in the marketplace by providing `displayName` field in the `package.json` manifest, so changing your extension displayed name to something like **Legacy Haxe 3.2.1** should be completely possible. In fact, I think Microsoft has done exactly the same things with their C# extensions.

As for the publisher name, I don't think it's possible to change that or provide a "display" name indeed, but then again it's not really important, as long as the choice what to install is obvious.

**Comment by jcward** [comment]
6 days of silence? Wow, time flies.

Ok, I've pushed an update to title vscode-haxe **Legacy Haxe 3.2.1**. I've also put a note in the README.md, which shows up on the marketplace page (once some cache times out, I assume.)

I still think it's not ideal to lose our download counts and publish under individual names, but meh, I suppose there's little that can be done.

Feel free to rename yours **Haxe** or **Haxe 3.3** or something.

Cheers, guys!

**Comment by nadako** [comment]
Hey, thanks for this! I think the current name (Haxe Support) is fine since apparently it's gonna become the main extension for Haxe once and after 3.3 is out. The language server does check the haxe version and also README mentions the minimum required Haxe version, so it should be fine.

Also I don't really see the reason for us to merge the download counts, because the plugins are totally different and not really replaceable by each other (since you can't e.g. use vshaxe on haxe 3.2 and earlier). So I think what we have currently is okay.

**Comment by pleclech** [comment]
Ok, I think i will not do any update to vshaxe as there is a new one being developed and i see it is much easier for a haxe member to get things done into the compiler parts.

Cheers.

**Comment by Simn** [comment]
"Easier" my ass, the better position support alone was hours of boring, monotonous work. Someone just had to do it.

https://github.com/HaxeFoundation/haxe/commit/b56d29a7783b6946594b10fc38a1da6a376f9256
https://github.com/HaxeFoundation/haxe/commit/56fae7a1de3f5d10a7408638a2239899e0a2b01d

**Comment by pleclech** [comment]
@Simn I didn't say easier in term of development ;)

**Comment by jcward** [comment]
Patrick and I worked around the shortcomings of the compiler - sure some of it was hacks, but when you don't have commit access to the compiler, you do what you can. And while I'm happy to let others carry the vscode torch, I'm still quite proud of our efforts and the people we supported. Cheers @pleclech!

**Comment by nadako** [comment]
> you don't have commit access to the compiler, you do what you can

you know this is an open-source project and you can get access rights if you contribute :)

**Comment by jcward** [comment]
You know Haxe Support is a stupid name, right? :)

**Comment by nadako** [comment]
Actually you have a point here. I think I named it after some popular language support extension, but I'm looking at the marketplace now and can't see any with a name like that. There's just `C#`, `Python`, `Go` etc, so yeah, probably we should rename it to just `Haxe`.

**Comment by nadako** [comment]
Oh, I found one, `Legacy C# Support`.

**Comment by nadako** [comment]
@jcward Oh, to clear up the potential misunderstanding, in that comment I wasn't trying to point out that you guys did something wrong. I'm just saying that we're very approachable for any constructive discussions about fixing/improving IDE support in the compiler and if you guys are willing to contribute to it in any way, including actual code, the lack of push rights shouldn't stop you.

And you and @pleclech did awesome job providing a working extension for vscode. One can't underestimate your work here. But the reasons for creating vshaxe mentioned in my first comment still stand.

**Comment by jcward** [comment]
No worries, cheers!

**Comment by pleclech** [comment]
@jcward @nadako @Simn 
Thanks.

It's ok, no problem at all :)
