### ISSUE TITLE
Hovering over an open bracket shows an empty brackets popup

### ISSUE THREAD

**Issue by mrcdk** [vshaxe/vshaxe#113]
![](http://i.imgur.com/eOz53Zj.png)
![](http://i.imgur.com/Fgc7luY.png)

It only happens with an open bracket `{`

I'm not sure if this is intentional or not but I'm guessing it isn't.

**Comment by nadako** [comment]
I _think_ that's just how Haxe parser works in display (completion) mode, since the requested position is on the open bracket it can't tell if it's a block expression or object declaration without parsing further, so it exists early. Not sure if this is something that can be dealt with in current Haxe parser (cc @Simn), but it's surely not a vshaxe/haxe-language-server issue, so I'm going to close this.

**Comment by EricBishton** [comment]
To be fair, the vscode plugin _could_ recognize that output from the compiler and just not build the tooltip.

**Comment by nadako** [comment]
That would require parsing on the plugin side, which is something we're yet to add.
