### ISSUE TITLE
Completion gets confused when working with macros / Context

### ISSUE THREAD

**Issue by jcward** [vshaxe/vshaxe#120]
After working on a macro project for a few hours, this problem seems to come and go, but right now it's stuck in this state: where it's very confused about `haxe.macro.Context`. It's convinced that Context has no static fields (error, currentPos, typeof, etc):

![image](https://cloud.githubusercontent.com/assets/2192439/25760494/3c5a90fc-3194-11e7-83d3-c7172453ae74.png)

I'm using 1.5.1, latest from market, and Haxe 3.4.2. Let me know if I can perform some debug steps to get you more info.

Best,
-Jeff

**Comment by Gama11** [comment]
See https://github.com/HaxeFoundation/haxe/issues/6000 - Not much to be done about this one the vshaxe side.

**Comment by nadako** [comment]
That's more of a Haxe issue. It tries to complete from within non-macro context, unless you're in the function with the `macro` specifier, and rightfully can't find those fields (since they are guarded with `#if macro`).

I'm not sure if we can do anything on vshaxe side, so I'm gonna close this. See https://github.com/HaxeFoundation/haxe/issues/6000

**Comment by jcward** [comment]
Ah, sorry for the double post. I searched, but maybe forgot `issues:closed` :)
