### ISSUE TITLE
'Find all references' feature

### ISSUE THREAD

**Issue by FrancisBourre** [vshaxe/vshaxe#14]
Hi.

To start, let me thank you and congratulate you again for the great work you provided one more time to the community. This IDE plugin is really promising.

I was just wondering if 'Find all references' feature was on your todo list and if it is a tricky one to implement.

Thanks again for all.

**Comment by Simn** [comment]
That is already implemented, but there's a potential problem because in order to find all references the compiler has to see all references first. A normal display compilation skips as many types as possible in order to speed up the result, which means it usually misses out on references.

This can be solved by compiling through the compilation server normally once in order to populate it. There's currently no good way of doing that though because the whole compilation server aspect is somewhat shadowed by vshaxe.

**Comment by nadako** [comment]
See vshaxe/haxe-languageserver#5
