### ISSUE TITLE
Clicking the trace hyperlinks in the debugger mode fails to open the corresponding file

### ISSUE THREAD

**Issue by starry-abyss** [vshaxe/vshaxe#165]
It tries to open <Project Root>/<FileName.hx> instead of <Project Root>/source/<Module Path>/<FileName.hx> for me

vscode 1.14.0
vshaxe 1.9.0
haxe-debug 1.1.2
Flash debugger

**Comment by Gama11** [comment]
Could you elaborate a bit? What are "trace hyperlinks"?

Did you mean to report this at https://github.com/vshaxe/vshaxe-debugadapter?

**Comment by starry-abyss** [comment]
I mean those:

![default](https://user-images.githubusercontent.com/11571820/29169545-32222cc2-7ddd-11e7-9ca1-d15f536e65d1.png)

Sorry, I don't know in what repo it should be reported, the guide https://github.com/vshaxe/vshaxe/blob/master/.github/CONTRIBUTING.md doesn't say to report to vshaxe-debugadapter in any case :D

**Comment by Gama11** [comment]
Ah... the thing is, VSCode just turns that into a link because it happens to look like a file path. This is more or less the same issue we had with adding a problem matcher for traces: https://github.com/vshaxe/vshaxe/issues/139#issuecomment-314529402

Unfortunately, we can't really do anything about it. Even if we _could_ change the link target, we don't know where the file is that the trace is referring to. Trace only prints the file name, not the path.

I updated the `CONTRIBUTING.md`.

**Comment by EricBishton** [comment]
You *could* read the project .xml to find the sources, classpath, and libraries that the compiler would use and then traverse that path until you find the file.  There may be duplicates, but that's what classpath ordering is for.

Traversing like this is essentially what the IDE has to do when using the hxcpp debugger, because hxcpp doesn't put complete paths in the stack frames, either.

**Comment by Gama11** [comment]
>There may be duplicates, but that's what classpath ordering is for.

We don't know the packages from the trace output either though, so it would be enough to have two .hx files with the same name - which wouldn't be a conflict, and probably quite common.

**Comment by EricBishton** [comment]
If you know it's a trace message, then you can examine the given line (by number) for each of the files to see which one it is.  If you don't, there's always a simple dialog to allow the user to resolve the conflict.  Just sayin'.
