### ISSUE TITLE
How to execute the resulted file?

### ISSUE THREAD

**Issue by hopewise** [vshaxe/vshaxe#17]
I need to execute the file (swf file) that is a result of a successful compilation, but I have no idea how to do so.

What I know is the full path of the file, so I need to run a command like double click on the file after compilation.. any idea?

**Comment by nadako** [comment]
To be honest, I'm not sure either. VSCode has these "launch configurations", but that's looks like it's only for debugging.

I think what you could do is make haxe run your file with `-cmd` arg. Try changing your `tasks.json` so that you have something like this:
```
{
...
    "command": "haxe",
    "args": ["build.hxml", "-cmd", "flashplayer", "yourfile.swf"],
...
}
```

Anyway, this is not really related to vshaxe, so I'm closing the issue.
