### ISSUE TITLE
Nice to have error message

### ISSUE THREAD

**Issue by MatthijsKamstra** [vshaxe/vshaxe#20]
I have un-installed Haxe to update it to the developers branch via brew.
(I have filed an issue here: https://github.com/HaxeFoundation/homebrew-haxe/issues/1)

After deletion, I started VSCode and got this message

```
The Haxe server crashed 5 times in the last 3 minutes. The server will not be restarted.
```

A `nice-to-have` would be to have a message mentioning that Haxe is not installed and how to install the latest and greatest.

**Comment by nadako** [comment]
Implementing this properly requires a bit of refactoring, since we start haxe server not on `onInitialize`, but on first `onDidChangeConfiguration` where we can't notify vscode that initialization has failed. Ideally, language server protocol should support "omg i crashed for good" notification or something like that, but it doesn't seem to, right now, so to handle this gracefully, we need to disable language server callbacks if haxe server failed to start so it doesn't spam errors to development console.

**Comment by fzzr-** [comment]
I think we need a "self-diagnostic" for plugin where we will check out:

* does `haxe` exist in PATH
* version of compiler
* validate User's preferences:
    * display arguments
    * something else

In case when we have got fatal or repeated error then run "self-diagnostic" and notify user. And run "self-diagnostic" before every server init.

**Comment by Gama11** [comment]
I made some further improvements here (the previous error could be a bit obscure):

If `haxePath` is just `"haxe"` (default), and the error was `ENOENT` (file not found), then we display this error:

![](http://i.imgur.com/wBsp7d8.png)

If `haxePath` is an absolute path, we print it and prompt the user to check his settings:

![](http://i.imgur.com/56Auk1m.png)

Otherwise, we just print the full error message from before:

![](http://i.imgur.com/qwE5gAO.png)

**Comment by Gama11** [comment]
The error handling we have now seems sufficient / user-friendly enough.
