### ISSUE TITLE
Haxe errors without location not added to problems view

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#214]
When a haxelib library is missing, the compiler will print an error and exit.
These errors are not reported in "Problems", you need to go look into the build Terminal to find them, which is not the best since when you launch with F5 you are prompted to open Problems to look for errors (The preLaunch task Build has exit with error code 1 --> show errors)

**Comment by Gama11** [comment]
Haxelibs errors don't really match the format that the Haxe problem matcher expects - there's no line numbers, no file, no character range, etc... We could add a separate `$haxelib` problem matcher or something like that, but it's a bit awkward since VSCode expects all problems to have a location, which means you can still click on them if they don't have one. Can't find the corresponding VSCode issue right now...

![](https://i.imgur.com/DhPhuUT.png)

This is similar to #139.

**Comment by Gama11** [comment]
I think each problem _matcher_ can only have one problem _pattern_. Also, I don't think output should by default be considered as an error, there should at least be an `Error:` prefix or something? Since there's traces etc..

The bigger problem IMO is that VSCode allows you to "open" problems without a location.

**Comment by ncannasse** [comment]
@Gama11 displaying is already good enough, even with no location, so yes from what I understand this requires a `Error : .*`  problem matcher. Do we already inject the problem matchers in haxe build tasks? If not, that's a good occasion to add boths :)

**Comment by ncannasse** [comment]
(and we should maybe actually reports everything that's written on stderr as errors, traces would go on stdout anyway)

**Comment by Gama11** [comment]
Yes, auto-generated tasks use the haxe problem matcher since they were introduced. It's still a bit annoying since VSCode copies the problem matchers into tasks.json when configuring a default build task. Maybe we could use the same regex for both...

I don't think we have any way to distuingish stderr / stdout with problem matchers.

**Comment by Gama11** [comment]
Note: this also affects other Haxe error messages without file / location info, such as those you get when you're missing hxcpp with `-cpp`:

```
Error: Library hxcpp is not installed
Error: Build failed
```

On the plus side, they all have the `Error:` prefix in common.

**Comment by Gama11** [comment]
With this, now have 4 problem matchers in total.. oh well. :) Also, VSCode seems to think these are from a file called `Error`:

![](https://i.imgur.com/CJnoMYl.png)

**Comment by ncannasse** [comment]
Thanks ! :)
