### ISSUE TITLE
Syntax highlight broken

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#219]
On some specific cases it seems syntax highlighting entirely stops working:

![image](https://user-images.githubusercontent.com/1022912/38469123-252bea86-3b50-11e8-88f4-5864cfb6d641.png)

(source file: 
https://github.com/HaxeFoundation/hashlink/blob/master/other/debugger/hld/Eval.hx)

**Comment by nadako** [comment]
Please open an issue here https://github.com/vshaxe/haxe-TmLanguage/issues

**Comment by Gama11** [comment]
It's caused by this line a bit further up:

```haxe
return { v : VArray(HDyn, vl.length, function(i) return vl[i], null), t : HDyn };
```

More specifically, the anonymous function. This means it's the same issue as https://github.com/vshaxe/haxe-TmLanguage/issues/3 and/or https://github.com/vshaxe/haxe-TmLanguage/issues/19, which have unfortunately proven to be quite difficult to fix.

Two possible workarounds:

- add braces: `function(i) { return vl[i], null) }`
- use an arrow function instead: `i -> vl[i]` (much nicer anyway)

**Comment by Gama11** [comment]
Actually, this issue seems more specific than I thought. Opened https://github.com/vshaxe/haxe-TmLanguage/issues/36.

**Comment by Gama11** [comment]
Ok, should be fixed.
