### ISSUE TITLE
Haxe Dependencies -> Haxe View

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#224]
A suggestion would be to change "Haxe Dependencies" to "Haxe View" and have:

- a `lib` directory for all dependencies (as of now)
- all other classes accessible through classpath (expect -lib of course)

**Comment by Gama11** [comment]
`-cp` dependencies are included.

**Comment by ncannasse** [comment]
Uhm, I only see the haxelib dependencies in vshaxe 1.11

**Comment by Gama11** [comment]
Only dependencies outside of the current workspace are shown, could that be it?

**Comment by ncannasse** [comment]
Yes. I would like to use it as an alternative workspace

Le jeu. 26 avr. 2018 12:15, Jens Fischer <notifications@github.com> a
écrit :

**Comment by Gama11** [comment]
As in, hide the normal file explorer view entirely and only use the Haxe dependencies view?

I'm not sure we want to encourage that, the regular file explorer view still has a lot more features: much more context menu items, drag and drop support, auto-detection of file changes etc etc... The Haxe dependencies view is intended to be used _in addition_ to it, not _instead_ of it. That's why classpaths outside of the current workspace are hidden, they would be redundant / appear twice.
