### ISSUE TITLE
Allow to disable Diagnostics Warnings

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#243]
Users should be able to tell which category of diagnostics warnings they want to get, for instance by adding:

```
"haxe.diagnostics.unused_variable" : "false"
```

to their VSCode settings.

**Comment by Gama11** [comment]
Maybe an array of "diangostic IDs" to disable would be better, to keep the settings from exploding too much. You'd still get nice completion of available IDs in there via JSON schemas.

**Comment by Gama11** [comment]
With vshaxe 2.1.0 (that was just released), unused code is now faded out instead of being marked as a warning. That might make this less of an issue? (and also looks nicer)

![](https://i.imgur.com/Vhi2OTP.png)

**Comment by Gama11** [comment]
Is this still an issue, now that unused code is presented differently (see previous comment)? The rest is just compiler errors, I don't think it would make sense to allow disabling specific compiler errors somehow / there's not really a good way to do that.

**Comment by ncannasse** [comment]
Sure, let's see how it goes.

**Comment by jcward** [comment]
I was going to file an issue to disable the "unused import" warning. However, this issue seems roughly the same. I agree with Nicolas -- I want control over any "automated warnings", especially because 1) my files may have imports for targets that aren't known by this completion server, and 2) warnings like that can cause merge conflicts as various developers may try to solve them separately.

Anyway, the "faded out import statements" in 2.1.0 is much nicer than the big list of warnings. Thanks.
