### ISSUE TITLE
Map complete to haxe.ds.Map

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#255]
```haxe
var scripts : Map<String,Bool> = new Map|
```

When opening the parenthesis here, it will expand to the following:

```haxe
var scripts : Map<String,Bool> = new haxe.ds.Map(|)
```

I don't think VSHaxe should follow the typedef here.

**Comment by Gama11** [comment]
Hm.. I think the real issue is that typedefs are missing from `new` completion. Normally you should see both types, and the toplevel one "already imported" should show up first:

![](https://i.imgur.com/17q5JZM.png)

However, the typedef is filtered out for `new`-completion. This is an issue on Haxe's end.

**Comment by Gama11** [comment]
https://github.com/HaxeFoundation/haxe/issues/7224
