### ISSUE TITLE
Include #if / #else / #elseif / #end in completion

### ISSUE THREAD

**Issue by Gama11** [vshaxe/vshaxe#275]
Probably should be done on the Haxe side. Things to consider:

- triggering completion at `#|` should work (currently is a parser error)
- it should work in inactive conditional compilation blocks

**Comment by EricBishton** [comment]
And, if you're going down that road, the completion should work for `-D` defined variables when you are in the conditional expression, e.g. `#if (cpp & |`.

**Comment by Gama11** [comment]
That's an interesting idea, if the compiler is doing it anyway.. It has a list of defines. Of course, only the ones _currently_ defined. Maybe target defines could be added separately.

**Comment by EricBishton** [comment]
Right.  The compiler already knows all of the target defines, so they should be available for completion.

**Comment by EricBishton** [comment]
Now, where you have an interesting interaction within vshaxe is when the user types `#if cpp || |` and forgot to put the leading parenthesis.  vshaxe could notice (possibly because there is a syntax error from the compiler?) and automatically add the parens.  

For example, `public function #if cpp || java inline #end myfunc()` is a syntax error, because the || java is not part of the `#if` condition.  That's why all complex conditions require parens.

**Comment by Gama11** [comment]
See https://github.com/HaxeFoundation/haxe/issues/8686.
