### ISSUE TITLE
Added brackets after select function

### ISSUE THREAD

**Issue by flashultra** [vshaxe/vshaxe#279]
When select 'stamp' from Timer brackets did not appear ,so I need to write them.  

![Brackets](https://media.giphy.com/media/2SYbxLeiEzRb4Le5EX/giphy.gif)

**Comment by Gama11** [comment]
It would be annoying to auto-insert them since you might not always want to _call_ the function, you might just want to store / pass a reference to it or [call `bind()` on it](https://haxe.org/manual/lf-function-bindings.html).

Instead, you can press `(`, which is a so-called "commit character" for functions. If you have `"editor.autoClosingBrackets"` enabled (which is the default), the `)` will be inserted automatically as well.

![](https://i.imgur.com/ndAhKVf.gif)
