### ISSUE TITLE
HXML language server

### ISSUE THREAD

**Issue by nadako** [vshaxe/vshaxe#28]
Just some ideas for IDE services for the HXML files:
- haxe argument completion (-cp/-lib/etc), obviously
- -D completion (from `--help-defines` and potentionally from https://github.com/HaxeFoundation/haxelib/issues/262)
- -D hover help (same as above)
- -cp and --cwd completion (filesystem, why not?)
- -lib completion (ideally we'd use haxelib as a library, but some ad-hoc solution would also work for now)
- --macro completion (most probably hard to get right)
- diagnostics: wrong -cp/--cwd, not-installed -lib, invalid --macro

**Comment by Simn** [comment]
I've worked a bit on this here: https://github.com/vshaxe/vshaxe/tree/hxml_server

Parsing all this cli output makes me want to commit sudoku though.

**Comment by Gama11** [comment]
We now have this: https://community.haxe.org/t/vshaxe-2-21-0-released-hxml-completion/2537

It's implemented as part of the regular Haxe language server rather than a separate one. Also, there's only completion and hover for now, no diagnostics. And no fancy completion features that "go into Haxe-land", like `--main` entry points or `--macro` - we would need some help from Haxe with those.
