### ISSUE TITLE
Infinite loop (in language server?)

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#281]
When doing some daily coding, we got an infinite loop.

I notice the following:

- haxe was at 0% cpu
- one of VSCode processes was at 25% cpu (100% on a single core, typical infinite loop)
- VSCode was stuck on "Generating..."

When killing this process we got a lot of the following logs, which I think are all aborted queued requests:

```
Error: Connection got disposed.
    at Object.dispose (C:\Users\PC\.vscode\extensions\nadako.vshaxe-2.3.0\node_modules\vscode-jsonrpc\lib\main.js:825:25)
```

I tried to look at what was the last request sent to the compiler, it was a hover on some file. I tried to replicate this hover going at the same position but was not able to trigger the infinite loop again.

**Comment by rb1147x** [comment]
I'm also seeing a spike in cpu usage and the same error.

I'm able to reproduce the problem whenever I write an import statement and notice a never ending progress indicator in the outline widget:

![outline](https://user-images.githubusercontent.com/17628197/44412728-42f1f800-a52f-11e8-9716-ba8b1a86cbb2.PNG)


I'm using haxe 3.4.7, not sure if it's related, but I do get an "Unable to build cache" error:

```
Haxe version does not support JSON-RPC, using legacy --display API.
Building Cache...
> Error: Invalid format: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"supportsResolve":true}}
```

I figured that would be just because I'm not using haxe 4, however, I'm including it just in case...

**Comment by Gama11** [comment]
@ncannasse https://github.com/HaxeFoundation/haxe/issues/7236 has been resolved, so this might be better now.

**Comment by ncannasse** [comment]
Haven't had infinite loops recently, will close for now.
