### ISSUE TITLE
Completion and highlighting not working

### ISSUE THREAD

**Issue by fullofcaffeine** [vshaxe/vshaxe#309]
I made sure to check that the file was saved :)

In fact, this is another project, and it has a somewhat unusual setup. It's an experiment of mine with integreating Haxe code in a TS project by using `hxgenjs`. The experiment works, but for some reason I can't get vshaxe to function well with the Test haxe class I have here: https://github.com/fullofcaffeine/ts_hx_test/blob/master/haxe_src/haxeintegration/Test.hx.

You can see in the sshot below that Haxe correctly shows the error when called from the console (`haxe build.hxml`):
![vshaxe](https://user-images.githubusercontent.com/81248/49844195-8cd54700-fd87-11e8-89cb-d87702109273.png)

You can check the contents of the `build.hxml` here: https://github.com/fullofcaffeine/ts_hx_test/blob/master/build.hxml

Maybe it's because of the way the class in being included with `--macro include`?

**Comment by Gama11** [comment]
Something in the project seems to trigger a compiler hang with 3.4.7, so I guess this is related to #303. But again, since that's a Haxe issue, and there's not really anything to be done about it on the vshaxe side of things. In this case, the hang seems to happen during the first completion request rather than "Building Cache" though.

The good news is that it seems to work fine with latest Haxe 4 (at least after commenting out the deprecated `Context.onMacroContextReused` call in hxgenjs).

![](https://i.imgur.com/dggKOve.png)
