### ISSUE TITLE
import like being on top

### ISSUE THREAD

**Issue by Simn** [vshaxe/vshaxe#325]
![2019-03-05_16-13-37](https://user-images.githubusercontent.com/634365/53815294-adb1d080-3f61-11e9-9278-f7457f315db0.gif)

```haxe
/**
	DON'T COPY MY CODE OR I KILL YOU
**/

package;

class Main {
	static public function main() {}
}
```

I think this was working at some point and I'm not sure what changed. This is not only ugly but also causes errors because imports are not supposed to show up before `package`.

**Comment by Gama11** [comment]
Hm, yeah, I remember wanting to rewrite import insertion with tokentree to make it smarter, but I don't think it used to be _that_ dumb...

**Comment by Gama11** [comment]
On second thought, perhaps it was always that dumb. There was a fix but I reverted it again:

https://github.com/vshaxe/haxe-languageserver/pull/27
https://github.com/vshaxe/haxe-languageserver/commit/32929f8e0da8375d9453b1b43c34b9adc955fb89

**Comment by Simn** [comment]
There's no way it has always been this dumb. I cannot work on a single file in std without breaking it...

**Comment by Gama11** [comment]
I think it has, if license headers are involved. Sould be fine without them. The logic is simply "find the first non-empty line, excluding `package` statements".

**Comment by joshtynjala** [comment]
It looks like the logic should be updated to include "and any comments that appear before a `package` statement"

**Comment by Gama11** [comment]
`package` is not mandatory in Haxe in case of toplevel files, and I think I've else seen some files that had `package` statements _before_ the license header (though that's a bit strange).

In any case, I plan to rewrite this using the token tree, which should allow making it a lot more solid. Perhaps even including insertion of imports at the right positions alphabetically.

Although on second thought, that's a bit tricky because we can't be sure we're not messing up the order wrt shadowing... would probably need some additional info from the compiler's display API for that...

**Comment by joshtynjala** [comment]
This continues to be rough working on a big project with license headers. All completion/hover/etc. stops working every time an import is added before the `package` statement, and I need to stop everything to move the import manually before I can continue. Maybe there's some way to do a partial/temporary fix that doesn't require addressing all of the edge cases?

**Comment by Simn** [comment]
Yeah, I'm surprised we're the only people complaining about this because this is very obnoxious.

**Comment by joshtynjala** [comment]
@Gama11 Thank you!

**Comment by Gama11** [comment]
>Maybe there's some way to do a partial/temporary fix that doesn't require addressing all of the edge cases?

I've opted for the permanent fix instead. ;) I hope I didn't forget about any cases, gotta do a bit of testing..
