### ISSUE TITLE
Wrong highlighting ranges if string literal contains out-of-bmp chars

### ISSUE THREAD

**Issue by RealyUniqueName** [vshaxe/vshaxe#343]
```haxe
"😧".length;
```
![img](https://i.imgur.com/7GNDNLX.png)

**Comment by Gama11** [comment]
@nadako You might know best whether this is an issue on the Haxe or language server side, as you've dealt with encodings in the display protocol before?

**Comment by nadako** [comment]
Ehm, IIRC we use UTF8 encoding for haxe<->ls interop, and IIRC ls<->vscode uses the same.

**Comment by nadako** [comment]
(and our lexer also uses UTF8 nowadays).

**Comment by Gama11** [comment]
Doesn't that mean it should work though?

**Comment by nadako** [comment]
Well, yes :) Could it be a VSCode bug?

**Comment by Gama11** [comment]
There's a bit of a war going on in the LSP repo atm, maybe that's related... https://github.com/Microsoft/language-server-protocol/issues/376

**Comment by nadako** [comment]
> nadako [21:07]
 i bet you checked the ranges?
 it should be `0...10` for `"<anysinglechar>".length`, right?

**Comment by Gama11** [comment]
>gama11 [9:20 PM]
but if the LSP in fact uses UTF-16, that emoji is 2 wide I guess?

**Comment by s1-en** [comment]
Same issue as #438. Are there any temporary fixes for this issue?

For now I've opted with storing the values in a separate class with a static variable to reference the actual characters I need because I feel working with escaped emoji hex code would not be good for my sanity.

So far that seems to step around the autocompletion thing since the problematic characters are tucked away in their own little space but I would love to hear about alternative approaches too.
