### ISSUE TITLE
Funny Completion

### ISSUE THREAD

**Issue by ncannasse** [vshaxe/vshaxe#352]
![image](https://user-images.githubusercontent.com/1022912/58783517-5c0cf680-85e1-11e9-8270-bfa6c4c47ac3.png)

That's original :D

__________

```haxe
class Main {
	static function main() {
		var b:haxe.io.Bytes;
		b.blit()
	}
}
```

**Comment by Gama11** [comment]
Sorry, but this is a useless issue report. Please provide a reproducible sample.

**Comment by ncannasse** [comment]
It's completion on haxe.io.Bytes blit :-/

**Comment by Gama11** [comment]
And I should've known that how exactly from the screenshot..? ;)

**Comment by ncannasse** [comment]
I thought you knew better the haxe std API :D

**Comment by Gama11** [comment]
Sorry to disappoint. ¯\_(ツ)_/¯

**Comment by Gama11** [comment]
The highlighting of the active parameter was based on string-matching, so this used to be a VSCode limitation. However, the API has since been extended to be able to avoid this via explicitly specifying ranges:

https://github.com/Microsoft/vscode/blob/816a31517667f1ed8b0098ef6e20273614c31d1b/src/vs/vscode.d.ts#L3091

Looks like we could even use it, since the LSP also has it.
