### ISSUE TITLE
Change package/imports on explorer events

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#411]
- Change package/imports on moving files/folders
- Change imports on files/folders renaming
- Add `package some;\n\n` for new files maybe (optional)

`vscode.workspace.onDidCreateFiles/onDidRenameFiles/onDidDeleteFiles` should help, if file moving is delete->create events.

**Comment by Gama11** [comment]
This is not something for which we'd use the VSCode API directly, there's a rename request in the Language Server Protocol. And that should ideally just be a thin abstraction layer for a rename method implemented directly in the compiler's display protocol.

I think this can be closed since it's already covered by other issues: 
- https://github.com/vshaxe/vshaxe/issues/287
- https://github.com/vshaxe/vshaxe/issues/188

>Add `package some;\n\n` for new files maybe (optional)

vshaxe does this already, and has for quite a while.
