### ISSUE TITLE
Duplicate tabs

### ISSUE THREAD

**Issue by RedHeadEatBread** [vshaxe/vshaxe#423]
If you add code sources to the project using "Add folder to workspace", then when you go to the file through a link in the terminal (ctrl + click), a new tab opens, even if the tab with this file is already open.

**Comment by Gama11** [comment]
Could you show a screenshot or preferably a .gif to show what you mean exactly?

Note that multi-root workspaces / add folder to workspace isn't supported by vshaxe yet (https://github.com/vshaxe/vshaxe/issues/170).

**Comment by RedHeadEatBread** [comment]
When creating a minimal example with an error, I realized that it was not the additional workspace folders that were to blame, but the fact that opening new tabs was case-sensitive.

![tabs](https://user-images.githubusercontent.com/50680881/76747593-7425bf00-678a-11ea-9dde-6109127ae8ee.gif)

If the folder with the code begins with an uppercase letter, and the path in the hxml file is written in lowercase , then we get duplicate tabs.

I apologize for the fact that I first misled, but in any case it seems that this needs to be fixed.

**Comment by Gama11** [comment]
Thanks for the .gif, that helps a lot. It shows that this isn't a vshaxe issue, since vshaxe's goto declaration opens the file with the correct casing.

If anything, it would be a compiler issue, since it's Haxe that's printing the error message with the incorrect casing (`src2` rather than `Src2`). However, even there it could be argued that it's user error, since you use the wrong casing in your HXML file (`-cp src2`).
