### ISSUE TITLE
Feature Request: Inlay Hints

### ISSUE THREAD

**Issue by ghost** [vshaxe/vshaxe#444]
Please note that lsp currently does not have any inbuilt mechanism for this. However, the rust-analyzer plugin has this feature - https://github.com/microsoft/language-server-protocol/issues/956#issuecomment-611106048

**Comment by Gama11** [comment]
Whlie I do like the feature, I think we're unlikely to support this while it's not even officially supported in the LSP. Due to limited manpower it makes more sense to focus on catching up with features that are actually part of the LSP, but not implemented in the Haxe language server yet (semantic highlighting, rename...).

**Comment by AlexHaxe** [comment]
closed with 2.25.0 release
