### ISSUE TITLE
How to debug when completion doesn't show up?

### ISSUE THREAD

**Issue by kevinresol** [vshaxe/vshaxe#5]
The completion works fine until I added some build macro to a class. The macro was quite complex I am not sure why it doesn't work. How could I debug that?

**Comment by nadako** [comment]
Try adding `-v` as the first argument here https://github.com/vshaxe/haxe-languageserver/blob/master/src/haxeLanguageServer/HaxeServer.hx#L28

Then recompile the server and look at the "vshaxe" output channel in the output panel at the bottom.

We really should make that configurable.

**Comment by Simn** [comment]
Yes, maybe a displayServerArgs config entry would be a good idea. I'm not sure what would be useful other than `-v`, but you never know.

**Comment by kevinresol** [comment]
```
Processing Arguments [--cwd,/Users/kevin/Codes/mongo,mongo.hxml,-D,display-details,--no-output,--display,/Users/kevin/Codes/mongo/src/mongo/Database.hx@554,-D,display-stdin]
Defines bson=0.1.0,buddy=1.4.1,dce=std,debug=1,display-details=1,display-stdin=1,display=1,display_details=1,display_stdin=1,haxe3=1,haxe_ver=3.3,hxnodejs=4.0.8,jquery_ver=11203,js-es5=1,js=1,js_es5=1,js_es=5,minject=2.0.0-rc.1,mongo=0.0.0,nodejs=1,promhx=1.0.21,source-header=Generated by Haxe 3.3.0 (git build development @ 18faa39),tink_core=1.0.0-rc.12,tink_io=0.2.0,tink_macro=0.7.1,tink_streams=0.0.1,tink_tcp=0.1.0,tink_url=0.0.4,true=1
Using signature d070d7126911848b0f8e737d8685233d
> /Users/kevin/Codes/mongo/src/mongo/Database.hx:12: characters 2-7 : Module mongo.Options does not define type DropDatabaseOptions
> /Users/kevin/Codes/mongo/src/mongo/Database.hx:13: lines 13-40 : Defined in this class
> /Users/kevin/Codes/mongo/src/mongo/Database.hx:12: characters 2-7 : Module mongo.protocol.Message does not define type ReplyDropDatabase
> /Users/kevin/Codes/mongo/src/mongo/Database.hx:13: lines 13-40 : Defined in this class
> /Users/kevin/Codes/mongo/src/mongo/Database.hx:12: characters 2-7 : Module mongo.Options does not define type IsMasterOptions
> /Users/kevin/Codes/mongo/src/mongo/Database.hx:13: lines 13-40 : Defined in this class
> /Users/kevin/Codes/mongo/src/mongo/Database.hx:12: characters 2-7 : Module mongo.protocol.Message does not define type ReplyDropDatabase
Stats = 1 files, 301 classes, 1195 methods, 3 macros
Time spent : 0.520s
```
I see this response, there is no completion response there. How could I tell the reason?

**Comment by nadako** [comment]
Alright, I've implemented the `haxe.displayServerArguments` setting for easy debugging (just set it to `["-v"]`), so I'm gonna close this one.

As for your actual issue, this looks very much like a problem in Haxe itself, so the report (with reproducible example if possible) should go there. I think I also had some issue with similar error messages when switching between different completion arguments without restarting Haxe server, so it definitely has some problems. vshaxe will try to workaround these by just restarting haxe server when configuration changes (vshaxe/haxe-languageserver#10), but the actual cause should be fixed in Haxe itself.
