### ISSUE TITLE
Haxe server leaves Electron process for every closed workspace

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#526]
I closed 360 electron zombies today. Open any Haxe project (creates processes for Extension Host and Haxe Server), close window, only Extension Host will be killed.
Can be reproduced on latest vshaxe release with latest stable VSCode on macOS, or VSCode Insiders on Ubuntu.

If you comment out this line, `ChildProcessEvent.Exit` event will be called, and both processes are terminated:
https://github.com/vshaxe/haxe-language-server/blob/cc200727900a7e3c27ae6770f9db898e7a33a068/src/haxeLanguageServer/server/HaxeConnection.hx#L29

**Comment by RblSb** [comment]
By spec seems like there should be shutdown -> exit events:
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#shutdown
But exit is not triggered on latest vscode for some reason, i think it is should?
https://github.com/vshaxe/haxe-language-server/blob/ac075763de985c1ce13f11796b512a624d542cb9/src/haxeLanguageServer/Context.hx#L273
Cannot find how shutdown event is generated, it is from vscode too?

**Comment by AlexHaxe** [comment]
while trying to figure out why e.g. inlay hint feature wasn't even available on language server side, I updated vscode engine version in `package.json` and suddenly Haxe extension wouldn't even start. turns out that `LanguageClient.onReady` was dropped and instead `LanguageClient.start` now returns a promise. [release notes](https://github.com/Microsoft/vscode-languageserver-node#3170-protocol-800-json-rpc-800-client-and-800-server) state that there was a rework of start and stop methods, which might be an indication of something changing in that area. 

switching from `onReady` to `start` obviously doesn't fix shutdown issues (but the upgraded version does give access to features like inlay hints). 

so this needs more investigation
