### ISSUE TITLE
vshaxe blocks codedox from running

### ISSUE THREAD

**Issue by player-03** [vshaxe/vshaxe#534]
Steps to reproduce:

1. Start with an undocumented function:

   ```haxe
   public function doThing(arg:String):Bool { /* ... */ }
   ```

2. Place your cursor on the line above and type `/**`.

   ```haxe
   /**
   public function doThing(arg:String):Bool { /* ... */ }
   ```

Expected result: [codedox](https://github.com/vshaxe/codedox) inserts a boilerplate comment. If left on default settings, that would be this:

```haxe
/**
 * [Description]
 * @param arg 
 * @return Bool
 */
public function doThing(arg:String):Bool { /* ... */ }
```

Actual result: vshaxe inserts the string `**/` after the cursor. codedox doesn't insert any text at all.

```haxe
/****/
public function doThing(arg:String):Bool { /* ... */ }
```

---

To prove vshaxe is at fault, I tried the following steps.

1. Disable all Haxe-related extensions. Result: obviously no comment completion happens anymore.
2. Enable codedox. Result: still no comment completion.
3. Enable vshaxe. Result: codedox begins working correctly, producing the "expected result" above.
4. (Optional) Enable all other Haxe-related extensions. Result: codedox continues working correctly.
5. Reload the VS Code window. Result: codedox stops working, producing the "actual result" above.

Without having looked at the code, my first guess is that this is an issue of load order. If codedox is allowed to register its hook(s) first, it gets to handle comment completion. But normally, vscode goes first and installs its own hooks.

**Comment by AlexHaxe** [comment]
codedox plugin (and others) fails to launch because of an exception thrown (`TypeError: Cannot assign to read only property '__class__' of object '[object String]'`). 
somehow a vshaxe compiled with Haxe nightly breaks all Haxe plugins not compiled with nightly.
so solution is to compile plugins with nightly version.

**Comment by Gama11** [comment]
That sounds like something that should maybe be fixed in the compiler?

**Comment by AlexHaxe** [comment]
Haxe 4.x produces: `String.prototype.__class__ = String;` whereas nightly produces `Object.defineProperty(String.prototype,"__class__",{ value : String, enumerable : false});`.
with vshaxe compiled to 4.x there seems to be no problem when accessing `__class__` directly. as soon as vshaxe is a nightly build that property seems to become readonly for every Haxe extension (probably due to `writable` property of `ObjectPropertyDescriptor` being false by default when defining a property).

**Comment by rainyt** [comment]
I have the same problem

**Comment by player-03** [comment]
Ok, it wasn't too hard to make codedox use the development build. vscode-checkstyle, on the other hand? You're on your own for that one.
