### ISSUE TITLE
Is haxe code formatting supported?

### ISSUE THREAD

**Issue by zack-z** [vshaxe/vshaxe#55]
Can not find a way to format haxe code, is this a supported scenario? This is very common operation do have it anywhere on the roadmap?

**Comment by Gama11** [comment]
No, this is not supported right now.

It wouldn't be trivial either, because there aren't really any code formatters for Haxe (that I know of). So either one would have to be written from scratch, or we would have to go the route that FD did (using a formatter that's actually intended for other languages, but heavily modify the config - AStyle in that case).

**Comment by Gama11** [comment]
I don't think we are going to include AStyle. For one it would mean using a modified source like FD does for it to work ok with Haxe (maybe we could use FD's, but still). And we would also need to ship vshaxe with three different AStyle binaries (Windows, Mac, Linux).

For now you could try using the [AStyle extension](https://marketplace.visualstudio.com/items?itemName=chiehyu.vscode-astyle) - should work for simple code at least. It can't be configured to format Haxe right now though, see [this issue](https://github.com/welkineins/vscode-astyle/issues/6). In the meantime, you could use [this branch](https://github.com/Gama11/vscode-astyle/tree/haxe) where I hacked in Haxe support for testing.
