### ISSUE TITLE
Null safety errors stay

### ISSUE THREAD

**Issue by RblSb** [vshaxe/vshaxe#601]
New challenger since https://github.com/vshaxe/vshaxe/issues/509
```haxe
@:nullSafety
class Main {
	static function main() {
		var obj:{
			?a:{
				?b:Int
			}
		} = {};
		if (obj?.a != null) {
			// build, comment out and recompile to see red comment
			trace(obj.a.b);
		}
	}
}
```

**Comment by RblSb** [comment]
Regression in https://github.com/vshaxe/vshaxe/commit/fe542e64d21ecfd05919d7f03d974148106a88dc
Another example (uncomment, build, comment, build to see red comment)
```haxe
@:nullSafety
class Main {
	static function main() {
		var a:Null<Int> = 2;
		if (a == null) return;
		// if (a == 2 && true) return;
		fun(a);
	}

	static function fun(v:Int) {
		trace(v);
	}
}
```

**Comment by kLabz** [comment]
Should be fixed by [9a60b11](https://github.com/vshaxe/vshaxe/commit/9a60b11181d53ec53efdc4af8d1cacac96681730)

Can you confirm when you have a moment please?

**Comment by kLabz** [comment]
Handled these in [d679aba](https://github.com/vshaxe/vshaxe/commit/d679aba479436d5d1dd2148d18b3065d9f36134e)

Now there's something I want to handle because this change is making it a bit worse:

Haxe compilation server forgets easily about warnings when there are no errors, so
* when not using diagnostics, they simply disappear from Problems until the module is invalidated
* when using diagnostics, they disappear until we run diagnostics again on current file; could be mitigated by triggering that call automatically but that wouldn't be needed if root cause was handled

**Comment by Simn** [comment]
I was wondering about this too. The problem with warnings is that everything still gets cached, and then never looked at again by the compiler.

I think this would require associating warnings with modules, similar to how `m_display` works. Shouldn't be thaaat difficult to handle.

**Comment by kLabz** [comment]
Yeah, was thinking about caching the warnings and see how it behaves

**Comment by RblSb** [comment]
Seems fine now, except recompilation without changes skips null safety errors on compiler side, but this is old bug.
Also found interesting case, here compilation error will be removed after you build, comment out `a = null;` and save file, without building again. So build error disappear just like display one (does not happen in 2.28.0). Something that will be cool to see for most errors in future.
```
@:nullSafety
class Main {
	static function main() {
		var a = 2;
		a = null;
	}
}
```

**Comment by kLabz** [comment]
Yeah it's pretty much the same thing happening: compilation server is not outputting the error, so it's missing from Problems view (can check compiler output with --connect).

Nothing more to fix on vshaxe / haxe LSP side here I think?

**Comment by RblSb** [comment]
Nice job with unification then, thanks!
