### ISSUE TITLE
Couldn't connect on 127.0.0.1:6000 with VSCode 1.82.0

### ISSUE THREAD

**Issue by DigiEggz** [vshaxe/vshaxe#602]
VSCode updated itself to [1.82.0](https://github.com/microsoft/vscode/releases/tag/1.82.0) and I immediately started getting the error `Fatal error: exception Failure("Couldn't connect on 127.0.0.1:6000")` whenever I try to compile to any target.

Below are the build details of my current version of VSCode:
```
Version: 1.82.0 (Universal)
Commit: 8b617bd08fd9e3fc94d14adb8d358b56e3f72314
Date: 2023-09-06T22:09:41.364Z
Electron: 25.8.0
ElectronBuildId: 23503258
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.4.0
```

**Comment by Syopic** [comment]
Yes, downgrading to 1.81.1 solves the problem

**Comment by giuppe** [comment]
A workaround is to explicitly launch
`haxe -v --wait 6000`
in a vscode terminal

**Comment by Soup-Wizard** [comment]
Seriously, THANK YOU ALL. I just started trying Haxe/Heaps last night and couldn't even get the Hello World file for heaps to compile. Reverting VS Code versions worked.

**Comment by kLabz** [comment]
Anyone reproduces this issue on linux?

**Comment by kisetil** [comment]
Hi, I have the same problem on Windows, a few days ago before the VS update everything worked correctly. Regards

**Comment by djaonline** [comment]
I've been having the same issue on my linux distro(void linux) since 1.78 version of vscode. https://github.com/vshaxe/vshaxe/issues/589

**Comment by Noobz4Life** [comment]
I found that putting this into your settings.json also fixes it without having to launch it through a terminal every time (only tested on linux though)
`
"haxe.displayServer": {
    "arguments": ["--server-connect 127.0.0.1:6000"]
}
`

**Comment by datee** [comment]
I had the same issue too! Had to downgrade VSCode to 1.18 ... is a fix possible?

**Comment by RblSb** [comment]
We added better connection error message to nightly, ao someone can test it and write what exactly unix error this is (maube @kLabz can rebuild this commit to make it available on build.haxe.org)
https://github.com/HaxeFoundation/haxe/commit/44c9abdbb176c261d42822e2e4003b4727054aff

**Comment by AlexHaxe** [comment]
after some testing on a Windows machine I found out what causes it and how to reproduce it:
on systems where `localhost` resolves to `::1` vshaxe will open port 6000 on `localhost` (== `::1`) while `haxe --connect 6000` will try to connect to `127.0.0.1` which obviously fails (with `No connection could be made because the target machine actively refuxed it.`).

so if your hosts file contains the line `::1  localhost` then you will likely run into that problem (that's also how you provoke it).

**Comment by RblSb** [comment]
Can be related to vscode change where v4 ips are not sorted first anymore?
https://github.com/microsoft/vscode/issues/192545

**Comment by AlexHaxe** [comment]
could be yes. 

I guess the solution would be to explicitly set hostname to `localhost` when running tasks via compilation server (so tasks and Haxe server use the same name).

**Comment by RblSb** [comment]
Hm, why not replace "localhost" with "127.0.0.1" instead, in vshaxe and lsp?

**Comment by AlexHaxe** [comment]
Haxe compiler defaults to 127.0.0.1 when no host is given, so maybe we just change haxe-languageserver to a fixed ip address instead of `localhost`.

**Comment by kLabz** [comment]
I'd think using `localhost` everywhere is a better idea.

> It is also important to note you cannot always use 127.0.0.1 for loopback. IPv6 only systems do not respond to such requests since their localhost is linked to the address : :1.

> Another significant difference between localhost and 127.0.0.1 is how the request is sent. The request does not go through the network card when pinging the loopback address with the localhost. On the other hand, running 127.0.0.1 does pass through the network card, which may be affected by firewall settings and configurations.

Plus other things like people actually wanting to use some other IP for localhost, etc

**Comment by AlexHaxe** [comment]
well, localhost somehow doesn't seem to work. not even on console.

on Windows I can `telnet ::1 6000` and get Haxe output, but `haxe --connect localhost:6000` doesn't seem to connect (and obviously `haxe --connect [::1]:6000` doesn't work, because Haxe uses split on `:` to separate host and port).

on Linux localhost doesn't work even though it resolves to 127.0.0.1. using `haxe --connect 127.0.0.1:6000` works however (as does `--connect 6000`). `telnet localhost 6000` successfully connects. 

comparing `haxe --connect localhost:6000` with `haxe --connect 6000` and `haxe --connect 127.0.0.1:6000` on Windows shows that localhost produces 

> Fatal error: exception Failure("Couldn't connect on localhost:6000")

whereas the other two show

> Fatal error: exception Failure("Couldn't connect on 127.0.0.1:6000 (No connection could be made because the target machine actively refused it.\r\n)")

tested with haxe_20230908125023_536c388_bin.zip from build artifacts (win64 binaries)

not sure what to make of it.

looking at Haxe source code, I believe it only supports IPv4 sockets for `--connect` so anything IPv6 cannot work without modifying Haxe first. basically ruling out anything using a hostname for connections, because a hostname can have an A and an AAAA record in DNS and Haxe wouldn't know which one to choose (and would have to try both IPv6 and IPv4 connections).

**Comment by Simn** [comment]
I'm happy to add IPv6 support to Haxe for this, but that doesn't really help us with the current problem because existing versions have to function anyway...

**Comment by kLabz** [comment]
I'm checking for ipv6 support in Haxe atm and it seems pretty straightforward
Not sure if there's a nice fix on vshaxe/haxe lsp side only that would cover all these :/

**Comment by kLabz** [comment]
@AlexHaxe Does `haxe --wait 127.0.0.1:6000` + `haxe --connect 127.0.0.1:6000` work on such a windows machine using `::1` as localhost?

**Comment by datee** [comment]
this does not work for me (windows 10/11)
```
haxe --wait 127.0.0.1:6000
Fatal error: exception Failure("Couldn't wait on 127.0.0.1:6000")
```

**Comment by AlexHaxe** [comment]
> ```
> haxe --wait 127.0.0.1:6000
> Fatal error: exception Failure("Couldn't wait on 127.0.0.1:6000")
> ```

you have some process already occupying port 6000. you can only have one combination of host and port open on a single system.

> ```
> # localhost name resolution is handled within DNS itself.
> #	127.0.0.1       localhost
> #	::1             localhost
> ```

try `ping localhost`, it's probably pinging `::1`.

**Comment by AlexHaxe** [comment]
@kLabz seems to be working. I'm going to do some more testing and then we can aim for a new version.

**Comment by AlexHaxe** [comment]
vshaxe version 2.30.0 was just released. you should now be able to upgrade to VSCode 1.82.x

**Comment by hoseyjoe** [comment]
vscode hashlink debugger stopped working around same time for me. Is this potentially the same fix?

**Comment by kLabz** [comment]
Seems likely indeed
