### ISSUE TITLE
Error from Haxe server

### ISSUE THREAD

**Issue by MatthijsKamstra** [vshaxe/vshaxe#64]
Current 1.0.0 version on OSX 10.11.6

I don't do a lot of macros, so this is one I found somewhere which I find usefull
```
package model.constants;
import haxe.macro.Context;
class App {
	public static var BUILD : String = getBuildDate();
	macro public static function getBuildDate() {
		var date = Date.now().toString();
		return Context.makeExpr(date, Context.currentPos());
	}
}
```

With the new update I got:

```
Haxe language server started
Initializing completion cache...
Done.
Error from Haxe server: /usr/local/lib/haxe/std/haxe/macro/Context.hx:293: characters 9-37 : Invalid call
src/model/constants/App.hx:12: characters 9-53 : Called from
src/model/constants/App.hx:7: characters 36-50 : Called from
Aborted
Error from Haxe server: /usr/local/lib/haxe/std/haxe/macro/Context.hx:293: characters 9-37 : Invalid call
src/model/constants/App.hx:12: characters 9-53 : Called from
src/model/constants/App.hx:7: characters 36-50 : Called from
Aborted
Error from Haxe server: /usr/local/lib/haxe/std/haxe/macro/Context.hx:293: characters 9-37 : Invalid call
src/model/constants/App.hx:12: characters 9-53 : Called from
src/model/constants/App.hx:7: characters 36-50 : Called from
Aborted
```

Current haxe version
Haxe Compiler 3.4.0 - (C)2005-2016 Haxe Foundation

Building still works

**Comment by nadako** [comment]
I'm not getting this error in a minimal example (App.hx with that content, included in the build), could you provide something reproducible? :)

**Comment by MatthijsKamstra** [comment]
I can confirm a minimal example seems to work without errors.
I have to investigate

**Comment by MatthijsKamstra** [comment]
This is weird... but it's back.. even in the minimal project.

The only thing changed is that I closed & opened the project again... (????)
```
package;
import model.constants.App;
class Main {
    static function main() {
        trace('Hello, world! ${App.BUILD}');
        trace(App.BUILD);
    }
}
```

error:
```
Haxe language server started
Initializing completion cache...
Done.
Error from Haxe server: /usr/local/lib/haxe/std/haxe/macro/Context.hx:293: characters 9-37 : Invalid call
src/model/constants/App.hx:15: characters 9-53 : Called from
src/model/constants/App.hx:11: characters 36-50 : Called from
Aborted
Error from Haxe server: /usr/local/lib/haxe/std/haxe/macro/Context.hx:293: characters 9-37 : Invalid call
src/model/constants/App.hx:15: characters 9-53 : Called from
src/model/constants/App.hx:11: characters 36-50 : Called from
Aborted
Error from Haxe server: /usr/local/lib/haxe/std/haxe/macro/Context.hx:293: characters 9-37 : Invalid call
src/model/constants/App.hx:15: characters 9-53 : Called from
src/model/constants/App.hx:11: characters 36-50 : Called from
Aborted
```

**Comment by brokenbeta** [comment]
I am also getting this intermittently on OSX, and I have no idea what's triggering it either. I put the sample code into a [repository](https://github.com/brokenbeta/vshaxe-completion-issue), and right now, I can't get completions for this codebase (it brings up the error output above).

I set the repo up a few weeks ago but didn't post this comment because just as I was writing it up, the error spontaneously stopped happening. I have no idea what I changed and it's broken again in the meantime. Maybe give it a few tries?

**Comment by VysotskiVadim** [comment]
@nadako , I was able to reproduce the issue using example given by @brokenbeta : [example](https://github.com/brokenbeta/vshaxe-completion-issue).
Could you please try to reproduce issue again?

**Comment by nadako** [comment]
Oh, I can reproduce this, but only with actual Haxe 3.4.2, not with current development version, which makes it a Haxe issue.

And this looks like some macro-in-macro type of issue. Because the module `Main` is being typed in macro context as well, it tries to call `getBuildDate` macro (for the `BUILD` var) while it's already in macro context, which doesn't really work in Haxe at the moment. If I move that function to a separate module and use it from `Main` - errors go away.

It's hard to say why there are no errors in Haxe dev, because macro intepreter was completely reworked, but macro-in-macro is still an issue to consider, so better be on the safe side and separate macro code from non-macro one.

Anyway, I don't see what we could fix on vshaxe side.

**Comment by VysotskiVadim** [comment]
@nadako, thanks for clear explanation!
