### ISSUE TITLE
Highlighting for @param tag and optional arg

### ISSUE THREAD

**Issue by wiggin77** [vshaxe/vshaxe#78]
Highlighting on @param tag for optional args is not working.  

<img width="454" alt="screen shot 2017-01-19 at 5 56 46 pm" src="https://cloud.githubusercontent.com/assets/5024605/22129058/cbd85ec4-de71-11e6-9ac7-ef19dc056b5a.png">

**Comment by Gama11** [comment]
This is intentional, the `?` is not part of the parameter's name.

**Comment by nadako** [comment]
@Gama11 are you talking about the doc comment (`@param ?obj`)? Because it really looks like `?obj` should be cyan like `str` above.

**Comment by Gama11** [comment]
I dont know...  I want to avoid encouraging people to include the question mark there, it looks quite strange to me. You wouldn't include default values like `= null` there either.
This used to be quite commom because FD's doc comment generation had a bug that would include question marks, but that was fixed eventually.

**Comment by nadako** [comment]
Oh, fine with me then. I thought it's normal practice to do that :)

**Comment by Gama11** [comment]
For the record, TypeScript highlighting behaves like that as well:

![](http://i.imgur.com/FH42Xa0.gif)

Alternatively, we could use the `"invalid"` scope for the question mark, but I think I'd rather just leave it as is:

![](http://i.imgur.com/lfCq40G.png)
