### ISSUE TITLE
Toggle code lens

### ISSUE THREAD

**Issue by mlms13** [vshaxe/vshaxe#94]
The code lens is a neat feature, but it would be nice to have a way to toggle its visibility (either with a keyboard shortcut or via the command palette), without having to edit my user settings.

**Comment by Gama11** [comment]
That's a good suggestion. I myself have it permanently disabled at the moment because it's often just annoying, and having to enable it via the settings is just cumbersome enough that I don't end up doing it in the situations where it _would_ come in handy.

**Comment by Gama11** [comment]
Ok, we now have a `Haxe: Toggle Code Lens` command:

![](http://i.imgur.com/fqYIIMz.gif)

As you can see in the gif, there's one small caveat: the lens don't refresh until you edit the file. To fix that, I think we will have to wait until https://github.com/Microsoft/language-server-protocol/issues/192 is resolved. I've opened a separate issue to keep track of that here: #95

I did not add any keyboard shortcut to the command, since we don't have any for any of the other commands either. Plus, it's always hard to find good ones with all the pre-assigned ones from VSCode itself or other extensions, so it's probably best to leave this up to the user. If you want a shortcut, you can add a keybinding like this in your `keybindings.json`:

```json
{
    "key": "f3",
    "command": "haxe.toggleCodeLens"
}
```

This feature should be available pretty soon in the upcoming 1.4.0 we want to make.

A note on the behavior:

The command edits the `"haxe.enableCodeLens"` setting in your `settings.json` (VSCode provides an API for that). It defaults to editing the global settings, and edits your workspace settings if `"haxe.enableCodeLens"` is already present there (as the command would otherwise have no effect).

**Comment by mlms13** [comment]
Thanks so much (for this change and for the awesome plugin in general)!

**Comment by fzzr-** [comment]
VSC have the building setting for toggling lens. Key-binding command is `typelens.toggle`. I think this feature "Toggle Haxe Lens" is extra and not needed. Sorry. IMHO.

**Comment by Gama11** [comment]
@fzzr- Do you mean `"editor.codeLens"`? That's a setting though, not a command.

I can't find any references to `typelens.toggle` on the default keybindings page:

![](http://i.imgur.com/G7oDzbt.png)

**Comment by fzzr-** [comment]
It was my mistake. That command from `typelens by kisstkondoros` ext.
